[package]
name = "telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
http = "1"
opentelemetry = "0.33"
opentelemetry_sdk = { version = "0.33", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.33", default-features = false, features = ["grpc-tonic", "trace"] }
tonic.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.34"
tracing-subscriber.workspace = true
